### ISSUE TITLE
Init Training

### ISSUE THREAD

**Issue by huey0528** [ZhengyiLuo/PHC#40]
Hi Luo. There is an error when I want to init pnn training with amass dataset. I checked the env_im_pnn.yaml file which the models path could not be empty. May I know which model should I use for init training process, whether the single primitive or others. Thanks. 

Command:
❯ python phc/run_hydra.py learning=im_pnn_big env=env_im_pnn robot=smpl_humanoid env.motion_file=data/amass/pkls/amass_isaac_im_train_take6_upright_slim.pkl exp_name=pnn

Error Message: 
Traceback (most recent call last):
  File "phc/run_hydra.py", line 338, in main
    runner.run(cfg)
  File "/home/arcaea/anaconda3/envs/mdm/lib/python3.7/site-packages/rl_games/torch_runner.py", line 139, in run
    self.run_train()
  File "/home/arcaea/anaconda3/envs/mdm/lib/python3.7/site-packages/rl_games/torch_runner.py", line 122, in run_train
    agent = self.algo_factory.create(self.algo_name, base_name='run', config=self.config)
  File "/home/arcaea/anaconda3/envs/mdm/lib/python3.7/site-packages/rl_games/common/object_factory.py", line 15, in create
    return builder(**kwargs)
  File "phc/run_hydra.py", line 260, in <lambda>
    runner.algo_factory.register_builder('im_amp', lambda **kwargs: im_amp.IMAmpAgent(**kwargs))
  File "/home/arcaea/data/physics/PHC/phc/learning/im_amp.py", line 41, in __init__
    super().__init__(base_name, config)
  File "/home/arcaea/data/physics/PHC/phc/learning/amp_agent.py", line 39, in __init__
    super().__init__(base_name, config)
  File "/home/arcaea/data/physics/PHC/phc/learning/common_agent.py", line 60, in __init__
    self.model = self.network.build(net_config)
  File "/home/arcaea/data/physics/PHC/phc/learning/amp_models.py", line 12, in build
    net = self.network_builder.build('amp', **config)
  File "/home/arcaea/data/physics/PHC/phc/learning/amp_network_pnn_builder.py", line 22, in build
    net = AMPPNNBuilder.Network(self.params, **kwargs)
  File "/home/arcaea/data/physics/PHC/phc/learning/amp_network_pnn_builder.py", line 37, in __init__
    self.model_base = self.task_obs_size_detail['models_path'][0]
IndexError: list index out of range

**Comment by ZhengyiLuo** [comment]
Hi! Sorry for the late reponse; I have fixed this issue in the latest push. Simply commenting out that line would work.
