### ISSUE TITLE
Question about H1 and G1

### ISSUE THREAD

**Issue by LGZ-BIT** [ZhengyiLuo/PHC#76]
Hi, when I ran `python phc/run_hydra.py project_name=Robot_IM robot=unitree_g1 env=env_im_g1_phc env.motion_file=sample_data/dance_sample_g1.pkl learning=im_pnn_big exp_name=unitree_g1_pnn sim=robot_sim control=robot_control learning.params.network.space.continuous.sigma_init.val=-1.7 ` and `python phc/run_hydra.py  project_name=Robot_IM   robot=unitree_h1      env=env_im_h1_phc env.motion_file=sample_data/sample_dance_h1.pkl learning=im_pnn_big   exp_name=unitree_h1_pnn_realsim_092924 sim=robot_sim control=robot_control `,some errors accured. Is this because of my hardware issues？？

Traceback (most recent call last):
  File "/home/user/anaconda3/envs/isaac/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/user/anaconda3/envs/isaac/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/user/git_code/PHC-master/phc/utils/motion_lib_real.py", line 423, in load_motion_with_skeleton
    queue.put(res)
  File "<string>", line 2, in put
  File "/home/user/anaconda3/envs/isaac/lib/python3.8/multiprocessing/managers.py", line 834, in _callmethod
    conn.send((self._id, methodname, args, kwds))
  File "/home/user/anaconda3/envs/isaac/lib/python3.8/multiprocessing/connection.py", line 206, in send
    self._send_bytes(_ForkingPickler.dumps(obj))
  File "/home/user/anaconda3/envs/isaac/lib/python3.8/multiprocessing/reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
  File "/home/user/anaconda3/envs/isaac/lib/python3.8/site-packages/torch/multiprocessing/reductions.py", line 569, in reduce_storage
    fd, size = storage._share_fd_cpu_()
  File "/home/user/anaconda3/envs/isaac/lib/python3.8/site-packages/torch/storage.py", line 337, in wrapper
    return fn(self, *args, **kwargs)
  File "/home/user/anaconda3/envs/isaac/lib/python3.8/site-packages/torch/storage.py", line 407, in _share_fd_cpu_
    return super()._share_fd_cpu_(*args, **kwargs)
RuntimeError: unable to open shared memory object </torch_18647_1058760512_445> in read-write mode: Too many open files (24)
Traceback (most recent call last):
  File "/home/user/anaconda3/envs/isaac/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/user/anaconda3/envs/isaac/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/user/git_code/PHC-master/phc/utils/motion_lib_real.py", line 423, in load_motion_with_skeleton
    queue.put(res)
  File "<string>", line 2, in put
  File "/home/user/anaconda3/envs/isaac/lib/python3.8/multiprocessing/managers.py", line 834, in _callmethod
    conn.send((self._id, methodname, args, kwds))
  File "/home/user/anaconda3/envs/isaac/lib/python3.8/multiprocessing/connection.py", line 206, in send
    self._send_bytes(_ForkingPickler.dumps(obj))
  File "/home/user/anaconda3/envs/isaac/lib/python3.8/multiprocessing/reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
  File "/home/user/anaconda3/envs/isaac/lib/python3.8/site-packages/torch/multiprocessing/reductions.py", line 569, in reduce_storage
    fd, size = storage._share_fd_cpu_()
  File "/home/user/anaconda3/envs/isaac/lib/python3.8/site-packages/torch/storage.py", line 337, in wrapper
    return fn(self, *args, **kwargs)
  File "/home/user/anaconda3/envs/isaac/lib/python3.8/site-packages/torch/storage.py", line 407, in _share_fd_cpu_
    return super()._share_fd_cpu_(*args, **kwargs)
RuntimeError: unable to open shared memory object </torch_18637_2472120915_450> in read-write mode: Too many open files (24)

**Comment by ZhengyiLuo** [comment]
Sigh; I guess the multi-processing fix I put in didn't fix it for everyone. 

Please try with the newest commit; where I disabled multiprocessing.
